server:
  port: 3000
  address: 0.0.0.0
#  ssl:
#    key-store: fullchain.pfx
#    key-store-password: privatekey
#    key-store-type: privatekey
#    key-password: PKCS12
  error:
    whitelabel:
      enabled: false
spring:
  cloud:
    gateway:
      routes:
      
        # Token Service
      
        - id: token-service
          uri: http://localhost:3001
          predicates:
            - Path=/api/v1/tokens/**
          filters:
            - RewritePath=/token-service/(?<segment>.*), /$\{segment}
  
  
        # Member Service
              
        - id: member-service
          uri: http://localhost:3002
          predicates:
            - Path=/api/v1/members/**
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
  
  
        # Verification Service
              
        - id: verification-service
          uri: http://localhost:3003
          predicates:
            - Path=/api/v1/verifications/**
          filters:
            - RewritePath=/verification-service/(?<segment>.*), /$\{segment}
  
  
        # View Service
              
        - id: view-service
          uri: http://localhost:3007
          predicates:
            - Path=/api/v1/views/**,/css/**,/js/**,/font/**,/svg/**,/favicon.ico
          filters:
            - RewritePath=/view-service/(?<segment>.*), /$\{segment}
            
            
        # Book Service
              
        - id: book-service
          uri: http://localhost:3004
          predicates:
            - Path=/api/v1/books/**
          filters:
            - RewritePath=/book-service/(?<segment>.*), /$\{segment}
          
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/api_gateway
    username: root
    password: privatekey
    hikari:
      idle-timeout: 300000
      max-lifetime: 297000
  application:
    name: API-Gateway
  data:
    redis:
      host: localhost
      port: 6379
      password: privatekey
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 50MB
token:
  secret: Y2hvcHBhLWRvbnQtYml0ZS1tZS1zcHJpbmctYm9vdC1qd3QtdGVzdC1zZWNyZXQta2V5LWNob3BwYS1kb250LWJpdGUtbWUtc3ByaW5nLWJvb3Qtand0LXRlc3Qtc2VjcmV0LWtleQo=
  issuer: Blanc-et-Noir