server:
  port: 3008
  address: localhost
#  ssl:
#    key-store: fullchain.pfx
#    key-store-password: privatekey
#    key-store-type: privatekey
#    key-password: PKCS12
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/log_service
    username: root
    password: privatekey
    hikari:
      idle-timeout: 300000
      max-lifetime: 297000
  application:
    name: Log-Service